### ISSUE TITLE
feat: Dev, feature/login_just_pass

### ISSUE THREAD

**Issue by gimquokka** [GIST-Netchallenge2021/GIST-NetChallenge2021-server#2]
## Feature description
Add git branch for develop, and feature/login_just_pass API that always response true to request

### Use cases
깃 브랜치 초기화

## Benefits

For whom and why.
개발용 브런치 생성 및 클라이언트 로그인 개발을 위해 항상 true을 반환하는 기능 개발

**Comment by koseyeon** [comment]
[feat] create user_image and user_info uplode api
